# Generated by Django 2.2 on 2021-08-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    def create_content(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        User.objects.create(
            username="admin", password="azerty1234",
            is_superuser=True,
            is_staff=True
        )
        user = User.objects.create(
            username="random_guy", password="azerty1234"
        )

        Category = apps.get_model('faq', 'Category')
        Category.objects.create(name="Un sujet important")
        category2 = Category.objects.create(name="Un sujet hazardeux")

        Answer = apps.get_model('faq', 'Answer')
        answer1 = Answer.objects.create(
            text="John is in the kitchen. Ha ha ha."
        )

        Question = apps.get_model('faq', 'Question')
        Question.objects.create(
            text="Where is John?",
            author=user,
            category=category2,
            answer=answer1
        )
        Question.objects.create(
            text="Ca fait combien 1 + 1?",
            author=user,
        )
        Question.objects.create(
            text="A quelle catégorie appartient ma question?",
            author=user,
        )

    dependencies = [
        ('faq', '0003_auto_20210826_1830'),
    ]

    operations = [
        migrations.RunPython(create_content),
    ]
